#!/usr/bin/env bash
. ucommon.sh

_USAGE="
Finds Unison terms.

Usage:
> ufind somedir
"
(( $# == 0 ))  &&  uexit

# TODO pipe breaks with, eg, '| head -n5'; that's why we use cat redundantly
echo "find-in.all $@" | _ucm0 | deprompt.sh > ufind.stdout  &&  cat ufind.stdout

